name: style

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/style.yaml
      - docs/.snippets/**
      - src/**
      - tests/**
      - justfile
      - pyproject.toml
      - uv.lock
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/style.yaml
      - docs/.snippets/**
      - src/**
      - tests/**
      - justfile
      - pyproject.toml
      - uv.lock

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.43.0

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.8.23

      - name: Run style
        run: just style
